services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: chat
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 3307:3306
